language: python

python:
    - "3.4"

install: "pip install -r requirements.txt"

before_script:
    - "chmod -R +x ./bin"
    - "./bin/isort.sh"
    - "flake8 --exclude=migrations --max-complexity 10 stregsystem"

script:
    - "stregsystem/manage.py test"
